# Generated by Django 5.1.1 on 2024-11-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
